### ISSUE TITLE
code error

### ISSUE THREAD

**Issue by wyf001** [WorldEditors/PostKS#2]
![image](https://user-images.githubusercontent.com/24860627/151510752-b3044f6b-46ff-4abe-b722-9cc028ccab14.png)

generator.py中predecessors = (                 candidates / self.V + self.pos_index.expand_as(candidates)).view(b * self.k)的结果是Float类型，无法使用index_select方法，这里为什么用candidates / self.V呢 。

**Comment by WorldEditors** [comment]
感谢关注。这看上去大概率是python版本问题，2.7版本"/"会保留整数，但py3之后必须用“//”才能保留整数。把"/"符号改成"//"符号试试？

说明一下， 这份代码目前已经停止维护。这一版本的代码不管是python还是torch都非常古旧，不能保证正确运行，只能作为参考。我们后续的工作都将基于[Knover](https://github.com/PaddlePaddle/Knover)开源，欢迎关注。

**Comment by wyf001** [comment]
谢谢
